version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Greeting
          Command: echo Hello world
      - run:
          name: Print the current time and date
          command: date
      - run:
          name: Execute the current script
          command:
            bash ./test.sh
dependencies:
  pre:
    - sudo apt-get update -y
    - sudo apt-get install -y libgdal-dev
    - sudo apt-get install -y postgis
    - sudo apt-get install -y postgresql-client
    - sudo apt-get install -y python-virtualenv
    - python -m venv venv
    - bash ./test.sh
